// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVQdL8CyV_g_NvYky3gqGOB1RNVNqZ7MQ',
    appId: '1:527336230091:web:ae575abbfed9e95ec7df4e',
    messagingSenderId: '527336230091',
    projectId: 'samsung-store-app',
    authDomain: 'samsung-store-app.firebaseapp.com',
    storageBucket: 'samsung-store-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXWJHq8bxVfsFh_tXVMppdE2w882FyxOU',
    appId: '1:527336230091:android:5bc5686f7153ee20c7df4e',
    messagingSenderId: '527336230091',
    projectId: 'samsung-store-app',
    storageBucket: 'samsung-store-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn5L39d8CHDVBTNBr6Ddj6r9mjNi-ydJU',
    appId: '1:527336230091:ios:616ed3f3c8700c39c7df4e',
    messagingSenderId: '527336230091',
    projectId: 'samsung-store-app',
    storageBucket: 'samsung-store-app.firebasestorage.app',
    iosBundleId: 'com.example.samsungStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn5L39d8CHDVBTNBr6Ddj6r9mjNi-ydJU',
    appId: '1:527336230091:ios:616ed3f3c8700c39c7df4e',
    messagingSenderId: '527336230091',
    projectId: 'samsung-store-app',
    storageBucket: 'samsung-store-app.firebasestorage.app',
    iosBundleId: 'com.example.samsungStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVQdL8CyV_g_NvYky3gqGOB1RNVNqZ7MQ',
    appId: '1:527336230091:web:bde4d04e374c965bc7df4e',
    messagingSenderId: '527336230091',
    projectId: 'samsung-store-app',
    authDomain: 'samsung-store-app.firebaseapp.com',
    storageBucket: 'samsung-store-app.firebasestorage.app',
  );
}
